
name: test
on:
  push:
    workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      -name: install modules
        run: |
              sudo yum install python 3.6 -y
              pip3 install pandas
              pip install azure-storage-blob

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
            python3 t2.py
